### ISSUE TITLE
Design better invoice visualization

### ISSUE THREAD

**Issue by samo98** [slovak-egov/einvoice#105]
UBL2.1 and D16B are widely used invoice formats, we should not develop our own visualization unless it is necessary.

Try to search for visualizations used elsewhere, ideally there will be some usable XSLT and we will have to add slovak translations only

**Comment by samo98** [comment]
https://github.com/itplr-kosit/xrechnung-visualization

**Comment by filipsladek** [comment]
At least simplified form has better visualization
