### ISSUE TITLE
Design more user-friendly form

### ISSUE THREAD

**Issue by samo98** [slovak-egov/einvoice#137]
Ideally talk to people creating invoices on daily basis (possibly get inspiration from some invoice software)
Consider:
- prefill some fields (maybe use some data from ÚPVS)
- ability to create invoice templates (so i don't have to fill my information from scratch every single time)
- Split form to several pages
- Having clickable structure of the form on the side -> after click on subsection show section fields

Should be tied with #90 so the new form follows government design

**Comment by filipsladek** [comment]
At least simplified version is user-friendly
