### ISSUE TITLE
BT-25 back to simplified form

### ISSUE THREAD

**Issue by filipsladek** [slovak-egov/einvoice#163]
http://dev.einvoice.mfsr.sk/invoiceDocumentation/businessTerms/BT-25
is needed for storno invoice.

**Comment by filipsladek** [comment]
Needs to be changed in the excel.

**Comment by MiroDanek** [comment]
BT-25 doplnený pod poradovým číslom 10 do sekcie Úvod v v prototype vo Figme.[https://www.figma.com/file/xKx9EAYtIRHcTLqecVDmiL/IS-EFA?node-id=7219%3A4852]

**Comment by MiroDanek** [comment]
BT-25 doplnený aj do excelu. Link na zdielanie tohto excelu (Dokumentacia pomocna_Aktualizovane) som zaslal z mojej sukromnej adresy mdanek2317@gmail.com zucastnenym 17.6.2021, 11:19 h..

**Comment by filipmatusak** [comment]
BT-25 added to form
