### ISSUE TITLE
BT-130 - zoznam kódov UNECERec21

### ISSUE THREAD

**Issue by xDanielSiska** [slovak-egov/einvoice#168]
BT-130 https://dev.einvoice.mfsr.sk/invoiceDocumentation/businessTerms/BT-130

Ak sa v tomto poli použije kód zo zoznamu kódov UNECERec21 tak pri vložení FA skončíme na chybe : [BR-CL-23]-Kód jednotky MUSÍ byť kódovaný podľa Odporúčania OSN/ECE 20 s rozšírením v Odporúčaní 21

+ v zozname kódov UNECERec21 kód „PA“ – poprosím „Malí balík“ opraviť na „Malý balík“ :D

**Comment by filipsladek** [comment]
@filipmatusak please solve both of these issues
