### ISSUE TITLE
Podanie - editovateľnosť názvu FA

### ISSUE THREAD

**Issue by xDanielSiska** [slovak-egov/einvoice#169]
Po vygenerovaní FA ma presunie na „Podanie“. 
Nebolo by fajn keby bolo pole s názvom FA editovateľné? Nech si ju užívateľ nemusí stiahnuť, u seba premenovať a nanovo vložiť.

**Comment by filipsladek** [comment]
Wy would the user download it rename and insert again?
Maybe I do not fully understand the flow you desire

**Comment by xDanielSiska** [comment]
Tým, že vlastne v sekcii "Moje faktúry" nikde nedoťahujeme názov FA tak to je možno jedno.
Ale tak na zamyslenie, že keď nejaký malý podnikateľ si bude klikať FA a vygeneruje a chce si ju stiahnuť do PC pre evidenciu či by nebolo fajn mať pole s názvom vygenerovanej FA(aktuálne invoice.xml) editovateľné nech si ju vie stiahnuť už s názvom aký chce?

**Comment by xDanielSiska** [comment]
Zahrnuté vo figme.
