### ISSUE TITLE
Dáta sa držia vo formulári aj po podaní FA.

### ISSUE THREAD

**Issue by xDanielSiska** [slovak-egov/einvoice#170]
Po vygenerovaní FA a po podaní sa vo formulári stále držia údaje. Je to želaný stav?

**Comment by filipsladek** [comment]
I think it might be fine, since you can reset it easily.
If not cleared you can easily issue multiple very similar invoices one by one.

**Comment by xDanielSiska** [comment]
Máš pravdu, za mňa ok.
